version: "3"
services:
  api-gateway:
    image: gcr.io/smart-car-insurance-hybrid/api-gateway:latest
    ports:
      - "81:3000"
  mongodb:
    image: mongo:3.6.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=UycjvlH5R54cJHfy44XGbvtXfGtXKweQ
    ports:
      - "27017:27017"
    volumes:
      - ~/mongodb_data:/data/db
